name: 'ng2fun'
version: 0.2.0
description: >
  Todo Angular2 Dart Example
environment:
  sdk: '>=1.4.0'
dependencies:
  browser: any
  angular2: ">=2.0.0-alpha.13 <3.0.0"

transformers:
  - angular2:
      entry_point: web/index.dart
      reflection_entry_point: web/index.dart
  - $dart2js:
      minify: true
      commandLineOptions: [--trust-type-annotations, --trust-primitives, --dump-info]
      #commandLineOptions: [--trust-type-annotations, --dump-info]
      #commandLineOptions: [--dump-info]
